# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_checkout_start:
    path: /{tokenValue}
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_shop_checkout_address

sylius_shop_checkout_address:
    path: /{tokenValue}/address
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        tokenValue: current
        _sylius:
            event: address
            flash: false
            template: SyliusShopBundle:Checkout:address.html.twig
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\AddressType
                options:
                    customer: expr:service('sylius.context.customer').getCustomer()
            repository:
                method: findOneBy
                arguments:
                    - {tokenValue: "expr:service('sylius.context.cart').getCart().getTokenValue()?:service('request_stack').getCurrentRequest().get('tokenValue')"}
            redirect:
                route: sylius_shop_checkout_select_shipping
            state_machine:
                graph: sylius_order_checkout
                transition: address

sylius_shop_checkout_select_shipping:
    path: /current/select-shipping
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: select_shipping
            flash: false
            template: SyliusShopBundle:Checkout:selectShipping.html.twig
            form: Sylius\Bundle\CoreBundle\Form\Type\Checkout\SelectShippingType
            repository:
                method: findOneBy
                arguments:
                    - {tokenValue: "expr:service('sylius.context.cart').getCart().getTokenValue()"}
            redirect:
                route: sylius_shop_checkout_select_payment
            state_machine:
                graph: sylius_order_checkout
                transition: select_shipping

sylius_shop_checkout_select_payment:
    path: /current/select-payment
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: payment
            flash: false
            template: SyliusShopBundle:Checkout:selectPayment.html.twig
            form: Sylius\Bundle\CoreBundle\Form\Type\Checkout\SelectPaymentType
            repository:
                method: findOneBy
                arguments:
                    - {tokenValue: "expr:service('sylius.context.cart').getCart().getTokenValue()"}
            state_machine:
                graph: sylius_order_checkout
                transition: select_payment
            redirect:
                route: sylius_shop_checkout_complete

sylius_shop_checkout_complete:
    path: /current/complete
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: complete
            flash: false
            template: SyliusShopBundle:Checkout:complete.html.twig
            repository:
                method: findOneBy
                arguments:
                    - {tokenValue: "expr:service('sylius.context.cart').getCart().getTokenValue()"}
            state_machine:
                graph: sylius_order_checkout
                transition: complete
            redirect:
                route: sylius_shop_redirect
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\CompleteType
                options:
                    validation_groups: 'sylius_checkout_complete'

sylius_shop_redirect:
    path: /current/redirect
    methods: [GET]
    defaults:
        _controller: SuluSyliusIntegrationPlugin:RedirectToSulu:redirect
