sulu_sylius_integration_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: SuluSyliusIntegrationPlugin:Greeting:staticallyGreet
        name: ~

sulu_sylius_integration_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: SuluSyliusIntegrationPlugin:Greeting:dynamicallyGreet
        name: ~
